# Generated by Django 5.0 on 2024-10-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
