# Generated by Django 5.0 on 2024-10-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0004_register_amount1_register_description1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='amount1',
        ),
        migrations.RemoveField(
            model_name='register',
            name='description1',
        ),
    ]
