# Generated by Django 5.0 on 2024-10-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0005_remove_register_amount1_remove_register_description1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deposit',
        ),
        migrations.AddField(
            model_name='register',
            name='amount1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='description1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
