# Generated by Django 5.0 on 2024-10-03 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0006_delete_deposit_register_amount1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='description1',
        ),
        migrations.CreateModel(
            name='Trangection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.register')),
            ],
        ),
    ]
